[package]
name = "inline-python"
version = "0.14.0"
description = "Inline Python code directly in your Rust code"
license = "BSD-2-Clause"
edition = "2018"
repository = "https://github.com/fusion-engineering/inline-python"
keywords = ["python", "inline", "embed", "macro"]
autoexamples = false

[dependencies]
inline-python-macros = { version = "=0.14.0", path = "./macros" }
pyo3 = { version = "0.24", default-features = false, features = ["auto-initialize"] }

[workspace]
members = ["examples", "ct-python"]
